import { cn } from "@/lib/utils";
import { AppQueryProvider } from "@/providers/AppQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Controle Interno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={cn(inter.variable, "dark")}>
      <body>
        <Toaster richColors />
        <AppQueryProvider>{children}</AppQueryProvider>
      </body>
    </html>
  );
}
